### PR TITLE
Add reusable copy button component

### PR DESCRIPTION
**Pull request by alsolovyev**
### Description:
This component is used to let the user to copy links, code snippets and more.

### Available props:
  - ariaLabel: label for better accessibility
  - class: additional class for the button
  - textToCopy: text to be copied to the clipboard (use '#' for anchor links)

### Usage examples:
```twig
{% include 'components/copy-button.twig' with { textToCopy: 'Lorem ipsum dolor'  } %}
{% include 'components/copy-button.twig' with { textToCopy: '#anchor-link-dolor' } %}
```

### Preview:
https://user-images.githubusercontent.com/20425619/204527463-9a760abd-accc-4531-a055-b457e99096ed.mov

### CODE REVIEW

**Comment by alsolovyev** [comment]
Can't find any tests related to frontend code. Do I need to provide any, or it's ok without them?

**Comment by nikmel2803** [comment]
> Can't find any tests related to frontend code. Do I need to provide any, or it's ok without them?

no tests for now, unfortunately 
we will test and review your feature soon, thank you for contributing

**Review by nikmel2803 — APPROVED** [review]

**Review by TatianaFomina — APPROVED** [review]
Everything looks fine  👍

**Comment by nikmel2803** [comment]
@alsolovyev merged! thank you for contribution. we will release it soon

**Pull request merged**
